# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WexerSDKSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WexerSDKSampleApp
  #pod 'WexerContentSDK', :git => "git@github.com:wexervirtual/WexerContentSDK-iOS.git"
  pod 'WexerContentSDK', :path => "../WexerContentSDK.podspec"

end
